2023-12-13T14:42:30.0258932Z [2023-12-13::14:42:30:UTC)] [INFO] >>> python /home/runner/work/adl-awsdeploy-cicd/adl-awsdeploy-cicd/AlightEngineering/adl-awsdeploy-cicd-d1.0.283/src/alight/foundation/app/deploy/postgres.py --base-arg-parser-config-file-location /home/runner/work/adl-awsdeploy-cicd/adl-awsdeploy-cicd/AlightEngineering/adl-awsdeploy-cicd-d1.0.283/config --base-arg-parser-config-file-name postgres-build-args.json --artifact-ddl-file /home/runner/work/adl-awsdeploy-cicd/adl-awsdeploy-cicd/local/postgres/adl-postgres-poc/1.0.9/ddl/file_max_ts.ddl --db-name postgres --db-user-name --db-host adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com --db-port 5432 --allow-destructive-operations False --cicdvar schema_name=test_cicd <<<
2023-12-13T14:42:30.1187822Z [2023-12-13 14:42:30,116] [postgres] [consolelogger] [<module>:14] [INFO]: "Running /home/runner/work/adl-awsdeploy-cicd/adl-awsdeploy-cicd/local/postgres/adl-postgres-poc/1.0.9/ddl/file_max_ts.ddl file on host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com. database: postgres"
2023-12-13T14:44:40.1529992Z [2023-12-13 14:44:40,151] [postgresdataapi] [consolelogger] [connect:30] [ERROR]: "Error connecting to the database: connection to server at "adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com" (10.17.232.142), port 5432 failed: Connection timed out
2023-12-13T14:44:40.1541164Z 	Is the server running on that host and accepting TCP/IP connections?
2023-12-13T14:44:40.1546339Z "
2023-12-13T14:44:40.1657625Z [2023-12-13 14:44:40,151] [postgresdataapi] [consolelogger] [execute_sql:45] [ERROR]: "Error executing SQL statement: connection to server at "adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com" (10.17.232.142), port 5432 failed: Connection timed out
2023-12-13T14:44:40.1663669Z 	Is the server running on that host and accepting TCP/IP connections?
2023-12-13T14:44:40.1666417Z "
