$ python test_postgresdataapi.py
[2023-12-09 19:25:40,285] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:25:40,285] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:25:41,426] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:25:41,705] [postgresdataapi] [consolelogger] [execute_sql:43] [INFO]: "SQL Statement executed successfully."
[2023-12-09 19:25:41,705] [test_postgresdataapi] [consolelogger] [test_create_table:31] [INFO]: "Test 'test_create_table' passed. Status: ('FINISHED',)"
[2023-12-09 19:25:41,705] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:25:41,705] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
.[2023-12-09 19:25:41,705] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:25:41,705] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:25:42,531] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:25:42,810] [postgresdataapi] [consolelogger] [execute_sql:43] [INFO]: "SQL Statement executed successfully."
[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [test_create_table:31] [INFO]: "Test 'test_create_table' passed. Status: ('FINISHED',)"
[2023-12-09 19:25:42,810] [postgresdataapi] [consolelogger] [execute_sql:46] [INFO]: "Error executing SQL statement: cursor already closed"
[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [test_select_from_table:42] [INFO]: "Test 'test_select_from_table' passed. Status: ('FAILED',)"
[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
.[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [setUp:11] [INFO]: "Setting up the test."
[2023-12-09 19:25:42,810] [test_postgresdataapi] [consolelogger] [setUp:13] [INFO]: "Connected to the database."
[2023-12-09 19:25:43,496] [postgresdataapi] [consolelogger] [connect:26] [INFO]: "Connected to the host: adl-com-d1-cdp-dcnexus.cgs723tlzdrk.us-east-1.rds.amazonaws.com, database: postgres"
[2023-12-09 19:25:43,681] [postgresdataapi] [consolelogger] [execute_sql:46] [INFO]: "Error executing SQL statement: relation "test_cicd.non_existent_table" does not exist
LINE 1: SELECT * FROM test_cicd.non_existent_table;
                      ^
"
[2023-12-09 19:25:43,681] [test_postgresdataapi] [consolelogger] [test_table_not_created:51] [INFO]: "Test 'test_table_not_created' passed. Status: ('FAILED',)"
[2023-12-09 19:25:43,681] [test_postgresdataapi] [consolelogger] [tearDown:20] [INFO]: "Tearing down the test."
[2023-12-09 19:25:43,681] [test_postgresdataapi] [consolelogger] [tearDown:22] [INFO]: "Closed the database connection."
.
----------------------------------------------------------------------
Ran 3 tests in 3.407s
